# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: CI

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  check:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo skipped
        
  build:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
      - run: yarn lint
      - run: yarn lerna run tsc
      - run: yarn test
      


  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    env:
      YARN_NPM_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{secrets.GH_TOKEN}}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - name: Publish packages with Lerna
        run: |
         
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "samuraitruong@hotmail.com"
          git remote -v
          yarn lerna run tsc
          yarn lerna publish --yes --conventional-commits
        env:
          HUSKY_BYPASS: true
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
          YARN_NPM_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
